version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
      - /Users/Personal/Downloads/VidNote-a3761284913d.json:/VidNote-a3761284913d.json
    environment:
      - JWT_KEY=asdf
      - MONGO_URI=mongodb://mongo:27017/vidnote
      - GOOGLE_APPLICATION_CREDENTIALS=/VidNote-a3761284913d.json
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
